# Main config file for icon theme.
theme = "hugo-icon"
baseURL = ""
languageCode = "en-AU"
title = "WACFWRU govt employment webinar"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Metadata
[params]
  author = "Mark Scheuerell"
  description = "Panel moderator"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "A primer on federal government employment"
  description = "A discussion about what, where, and how"

# Navigation section
[params.nav]
  mission = "Information"
  services = "Services"
  team = "The presenters"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/eagle.jpg"
    [[params.mission.images.list]]
      img = "images/bear_lake.jpg"
    [[params.mission.images.list]]
      img = "images/LTR_top.jpg"
    [[params.mission.images.list]]
      img = "images/sockeye2.jpg"

  [[params.mission.item]]
    weight = 1
    name = "background"
    title = "background"
    subtitle = ""
    description = "<p>We recognize that it can be difficult for graduate students and post-docs to navigate the various options for employment in the federal government. This webinar will help demystify the various career options, the agencies that focus on environmental science, and how one goes about applying for those jobs."

  [[params.mission.item]]
    weight = 2
    name = "format"
    title = "Format"
    subtitle = ""
    description = "Sarah and Mark will describe their personal journeys to and in federal service, the pros and cons of federal employment, and how to maximize your chances of landing a federal position.<br><br>You can find the slides [here](https://github.com/wacfwru/govt_jobs/blob/master/webinar/federal_jobs_webinar.pdf).<br><br>You can watch a recording of the webinar [here](https://www.youtube.com/watch?v=Oqhw8scX9L8)."

  [[params.mission.item]]
    weight = 3
    name = "FAQ"
    title = "FAQ"
    subtitle = ""
    description = "Click [here](https://github.com/wacfwru/govt_jobs/tree/master/FAQ) for a list of frequently asked questions."

# Team section
[params.team]
  enable = true
  title = "Meet the presenters"
  description = ""

  [[params.team.item]]
    name = "Dr. Sarah Converse"
    position = ""
    description = "Dr. Converse is the Unit Leader of the U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit (WACFWRU). She is also an associate professor in the School of Aquatic and Fishery Sciences and the School of Environmental and Forest Sciences. Prior to joining the WACFWRU and UW, Sarah spent 10 years as a research ecologist with the U.S. Geological Survey's Patuxent Wildlife Research Center. Dr. Converse received her PhD in Wildlife Biology from Colorado State University."
    img = "images/sarah.jpg"
    email = "sconver@uw.edu"
    twitter = "https://twitter.com/conversesj"
    website = "https://fish.uw.edu/faculty/sarah-converse/"

  [[params.team.item]]
    name = "Dr. Mark Scheuerell"
    position = ""
    description = "Dr. Scheuerell is the Assistant Unit Leader for Fisheries of the U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit (WACFWRU). He is also an associate professor in the School of Aquatic and Fishery Sciences. Prior to joining the WACFWRU and UW, Mark spent 16 years as a research biologist with the National Marine Fisheries Service. Dr. Scheuerell received his PhD in Zoology from the University of Washington."
    img = "images/mark.jpg"
    email = "scheuerl@uw.edu"
    twitter = "https://twitter.com/mark_scheuerell"
    website = "https://fish.uw.edu/faculty/mark-scheuerell/"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2020 Mark Scheuerell <br> <a href='https://github.com/wacfwru/govt_jobs/' target='_blank'>Design</a> based upon the Hugo Icon theme by <a href='https://github.com/SteveLane/' target='_blank'>Steve Lane</a></small></p>"
  #github = "#"
  #twitter = "#"
  #facebook = "#"
  #vine = "#"
  #linkedin = "#"
  #instagram = "#"
  
